server:
  port: 0
  
spring:
  application:
    name: staff-service
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'