server:
  port: 8081
  
spring:
  application:
    name: admin-service
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'